### ISSUE TITLE
options: limit not working 

### ISSUE THREAD

**Issue by gauss1986** [namara-io/namara-python#4]
According to the description,

options = {
  'offset': 0,
  'limit': 1000
}
namara.get('faf672bc-6ed4-4048-8aaf-0e14039d9ff3', 'en-0', options)

should return 1000 rows of records (the dataset has 386k rows) while it actually returns the default 250 rows.

![screen shot 2018-04-27 at 11 29 20 am](https://user-images.githubusercontent.com/20598261/39370963-4b38f328-4a0e-11e8-83be-64768b6d8460.png)

**Comment by broneks** [comment]
limit max value is `250`
